### PR TITLE
Code review of interpolator_proxy

### PR DESCRIPTION
**Pull request by nwolek**
This includes commits from pull request #35 (only because it has not been merged yet) 
and a lot of work to solve issue #34 (but does not close the issue yet)

I have created a new object that I would like @tap to review. It is called `interpolator_proxy` and should allow other objects (like `delay` and `oscillator`) to provide a choice for their interpolation. The design takes into account:

- all memory should be allocated at compile time
- objects may want to instantiate one object, then select between any available interpolator option
- changes to interpolator option should be prevented from making bad choices

For this reason, `interpolator_proxy` does the following:

- constructor creates a vector with one of each available interpolator
- maintains a private index to the current interpolator choice
- requires changes to index are made via an enumerated list

Note that making this new proxy required that certain features of the derived classes become virtual members of the `interpolator::base` class. Also the proxy and enum will need to be updated as new interpolator options are added.

I don't think we currently have anything like this in the min-lib, so I am curious to see what @tap thinks before moving forward. It provides path to solving issues #34 and #31, but you may have another idea of how to tackle this. Thanks.

### CODE REVIEW

**Comment by nwolek** [comment]
During a Skype with @tap today, he suggested that [std:variant](http://en.cppreference.com/w/cpp/utility/variant) may provide the basis for an alternate design solution. I am going to review [this talk by Ian Hobson](https://www.youtube.com/watch?v=m7xYX8f8A7Y) on the topic and report back before deciding on this merge.

**Comment by nwolek** [comment]
Watched the video and also read these sources:

- [A true heterogeneous container in C++](https://gieseanw.wordpress.com/2017/05/03/a-true-heterogeneous-container-in-c/) 
- [std::visit is everything wrong with modern C++](https://bitbashing.io/std-visit.html)
- [Inheritance vs std::variant](http://cpptruths.blogspot.com/2018/02/inheritance-vs-stdvariant-based.html)

A few notes:

- Ian Hobson describes a problem similar to that I am facing while designing `interpolator_proxy`. He wanted to switch between oscillators without have to maintain instances of all of the options in memory simultaneously. Despite an extensive test of std::variant, he ended up doing exactly that (maintaining all options as instances _without_ using std::variant).
- The [std::visit](http://en.cppreference.com/w/cpp/utility/variant/visit) seems to be for performing the same function on all instances within the std::variant and negotiating the different datatypes. That is not what we need to do in interpolator. Instead, we want to call one specific interpolator function from among all the choices.

After all that, I am of the opinion that [std::variant](http://en.cppreference.com/w/cpp/utility/variant) might provide only a minor clarification of what the `m_type_vector` is doing, and would potential make other sections of the code less clear. It would not be a major improvement. In addition it sems that it would effect the underlying function and not the interface for using the proxy.

@tap can you look at [this section of test code](https://github.com/nwolek/min-lib/blob/issue/34/test/interpolator/interpolator_test.cpp#L713) and tell me if this is the syntax is what we hope to achieve? If yes, then I say we move forward with the current design.

**Comment by nwolek** [comment]
I am open to another name. I only chose "proxy" after looking through the GoF Design Patterns book and deciding that "proxy" was the pattern that most closely matched what I was doing. I'll defer to you on the matter of best name.

**Comment by nwolek** [comment]
@tap - These two commits should complete the name changes we discussed on Skype today. Tests for interpolator are passing.

**Comment by tap** [comment]
Got it. Thanks!

**Pull request merged**
